name: RapidCMD
main: rapidcmd\RapidCMD
version: 1.0.0
api: 1.10.0
load: STARTUP
author: Gamecrafter
description: 
website: https://github.com/Gamecrafter/PocketMine-Plugins/tree/master/RapidCMD
permissions:
 rapidcmd:
  default: op
  children:
   rapidcmd.command:
    default: op
    children:
     rapidcmd.command.rapidcmd:
      default: op